name: "Publish to NuGet"
description: "Automatic project detection, better error detection and better logging. Drop-in replacement for publish-nuget clones."

inputs:
  NUGET_KEY:
    description: "NuGet API key to authenticate on NuGet server. DO NOT PUT KEY DIRECTLY IN HERE. Use Secrets function in GitHub for example, i.e. dollarsign{{secrets.YOUR_NUGET_API_KEY}}."
    required: true
  PROJECT_FILE_PATH:
    description: "Full path to project file. (Example: src/MyNuGetProject/MyNuGetProject.csproj) (Default: Will scan all .csproj/.fsproj/.vbproj files and use first it finds that has GeneratePackageOnBuild set to true.)"
    required: false
  NUGET_SOURCE:
    description: "URL to NuGet server. (Default: https://api.nuget.org)"
    required: false
    default: "https://api.nuget.org"
  INCLUDE_SYMBOLS:
    description: "Add symbols to NuGet package. (Default: false)"
    required: false
    default: false
  TAG_COMMIT:
    description: "Current Git commit should be tagged upon successful upload to NuGet. Note: This will prevent publish if tag already exists. (Default: false)"
    required: false
    default: false
  TAG_FORMAT:
    description: "Name of Git tag. * will be replaced by version number. (Default: v*)"
    required: false
    default: "v*"
  PACKAGE_NAME:
    description: "NuGet package name. This is used for checking NuGet server if package version already exists. (Default: name extracted from PROJECT_FILE_PATH)"
    required: false
  VERSION_FILE_PATH:
    description: "Path to file containing version number to extract using regex. (Default: $PROJECT_FILE_PATH)"
    required: false
  VERSION_REGEX:
    description: "Regex pattern to extract version info in a capturing group. (Default: ^\\s*<Version>(.*)<\\/Version>\\s*$)"
    required: false
    default: "^\\s*<Version>\\s*(.*?)\\s*<\\/Version>\\s*$"
  VERSION_STATIC:
      description: "Useful with external providers like Nerdbank.GitVersioning where you could for example set it to variable (dollar){{env.GitBuildVersionSimple}}. Ignores VERSION_FILE_PATH & VERSION_REGEX."
      required: false
  REBUILD_PROJECT:
    description: "Rebuild project in release mode? You may turn this off if you have built project in previous step. (default: true)"
    required: false
    default: true
  LOG_LEVEL:
    description: "Log level (DEBUG, INFO, WARN). (default: DEBUG)"
    required: false
    default: DEBUG
  

outputs:
    VERSION:
        description: "Version of the associated git tag."
    PACKAGE_NAME:
        description: "Name of the NuGet package generated."
    PACKAGE_PATH:
        description: "Path to the generated NuGet package."
    SYMBOLS_PACKAGE_NAME:
        description: "Name of the symbols package generated."
    SYMBOLS_PACKAGE_PATH:
        description: "Path to the generated symbols package."

runs:
    using: "node22"
    main: "action.js"

branding:
    icon: package
    color: blue